version: "3.8"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph_data:/dgraph
    networks:
      - no-fun-neal
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph_data:/dgraph
    networks:
      - no-fun-neal
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0

  ratel:
    image: dgraph/ratel:latest
    networks:
      - no-fun-neal
    ports:
      - 8000:8000

  mongo:
    image: mongo:latest
    #container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
    volumes:
      - mongodb_data:/data/db
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    networks:
      - no-fun-neal
  mongo-express:
    image: mongo-express
    container_name: my_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo_express_admin_username
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_express_admin_password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/mongo_express_basic_auth_username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongo_express_basic_auth_password
    depends_on:
      - mongo
    secrets:
      - mongo_express_admin_username
      - mongo_express_admin_password
      - mongo_express_basic_auth_username
      - mongo_express_basic_auth_password
    networks:
      - no-fun-neal

networks:
  no-fun-neal:

volumes:
  dgraph_data:
  mongodb_data:

secrets:
  mongodb_root_username:
    file: ./secrets/mongodb_root_username.txt
  mongodb_root_password:
    file: ./secrets/mongodb_root_password.txt
  mongo_express_admin_username:
    file: ./secrets/mongo_express_admin_username.txt
  mongo_express_admin_password:
    file: ./secrets/mongo_express_admin_password.txt
  mongo_express_basic_auth_username:
    file: ./secrets/mongo_express_basic_auth_username.txt
  mongo_express_basic_auth_password:
    file: ./secrets/mongo_express_basic_auth_password.txt
