version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
    volumes:
      - mongodb_data:/data/db
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    networks:
      - no-fun-neal

  mongo-express:
    image: mongo-express
    container_name: my_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo_express_admin_username
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_express_admin_password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/mongo_express_basic_auth_username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongo_express_basic_auth_password
    depends_on:
      - mongodb
    secrets:
      - mongo_express_admin_username
      - mongo_express_admin_password
      - mongo_express_basic_auth_username
      - mongo_express_basic_auth_password
    networks:
      - no-fun-neal

networks:
  no-fun-neal:
    external: true

secrets:
  mongodb_root_username:
    file: ../secrets/mongodb_root_username.txt
  mongodb_root_password:
    file: ../secrets/mongodb_root_password.txt
  mongo_express_admin_username:
    file: ../secrets/mongo_express_admin_username.txt
  mongo_express_admin_password:
    file: ../secrets/mongo_express_admin_password.txt
  mongo_express_basic_auth_username:
    file: ../secrets/mongo_express_basic_auth_username.txt
  mongo_express_basic_auth_password:
    file: ../secrets/mongo_express_basic_auth_password.txt

volumes:
  mongodb_data:
